---
title: "Analysis for generation of Figure 2 - HD Allograft Model"
author: "John Mariani"
date: "12/6/2022"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "..")
```


```{r, echo = TRUE, message=FALSE, warning=FALSE}
library(Seurat)
library(scPlottingTools)
library(ggplot2)
library(tidyr)
library(FSA)
library(dplyr)
library(MAST)
library(FSA)
library(plyr)
library(xlsx)
library(patchwork)
library(ggplot2)
library(scales)
library(ggVennDiagram)

`%not in%` <- function(x, table) is.na(match(x, table, nomatch = NA_integer_))


axisTitleSize <- 8
axisTitleSize <- 6
axisTextSize <- 6
labelFont = 6
titleFont = 8

```


# Load and subset paradigm data

```{r}
merged <- readRDS("RDS/mergedUpdated.rds")


dimPlotColors <- c(cGPC = "green3", GPC = "orange1", "Immature Oligodendrocyte" = "royalblue2", APC = "brown3", Astrocyte = "purple3", NPC = "magenta")
cellTypeOrder <- c("cGPC", "GPC", "Immature Oligodendrocyte", "NPC", "APC", "Astrocyte")
merged$CellType <- factor(merged$CellType, levels = cellTypeOrder)

g20RescueSubset <- subset(merged, subset = otherGroup %in% c("G20 Neonatal Alone Late", "G20 Neonatal Rescue", "G19 Adult Rescue", "G19 Adult Alone Late"))

g20RescueSubset$Label <- mapvalues(g20RescueSubset$otherGroup, c("G20 Neonatal Alone Late", "G20 Neonatal Rescue", "G19 Adult Rescue", "G19 Adult Alone Late"), c("HD Ctr", "HD Allograft", "WT Allograft", "WT Ctr"))
g20RescueSubset$Label <- factor(g20RescueSubset$Label, levels = c("WT Ctr", "WT Allograft", "HD Ctr", "HD Allograft"))
g20RescueSubset$Label <- droplevels(g20RescueSubset$Label)




```

# Make Cell Type Stacked Plot

```{r}

g20RescueSubsetMeta <- g20RescueSubset@meta.data

g20RescueStackedCelltype <- as.data.frame(table(g20RescueSubsetMeta$Label, g20RescueSubsetMeta$CellType))


### Stacked Plot
stackedPlotG20Rescue <- ggplot(g20RescueStackedCelltype, aes(fill = Var2, y = Freq, x = Var1))+
  geom_bar(position = "fill", stat = "identity")+
  guides(fill = guide_legend(override.aes = list(size = .6))) +
  #scale_fill_manual(values = palette )+
  labs(y = "Percent", x = "Sort", fill = "Cell Type") + theme_classic() + scale_y_continuous(expand = c(0,0)) + ylab("Percent Identity") + theme(plot.tag = element_text(size = 12), legend.key.size = unit(.6, "lines"), text = element_text(size = labelFont), legend.position = "bottom", axis.text.x =element_text(angle = 45, vjust = .5, hjust = .5)) + xlab(element_blank())+
  theme(axis.text = element_text(size = axisTextSize), axis.title = element_text(size = axisTitleSize), plot.title = element_text(size = 18), legend.text = element_text(size = 18)) + ylab(element_blank()) + NoLegend()+
  scale_fill_manual(values = dimPlotColors) 

stackedPlotG20Rescue

#write.xlsx("SourceData/Fig2SourceData.xlsx", sheetName = "Fig2D", x = g20RescueStackedCelltype, row.names = F)



```

# Make DE Venn Diagram
```{r}

allDE <- read.delim("DE/allDE.txt")
table(allDE$Label)

rescueVennGenes <- list("WT Ctr vs HD Ctr" = allDE[allDE$Label == "WT Ctr vs HD Ctr",]$Gene,
                        "WT Allograft vs HD Allograft" = allDE[allDE$Label == "WT Allograft vs HD Allograft",]$Gene,
                        "WT Allograft vs WT Ctr" = allDE[allDE$Label == "WT Allograft vs WT Ctr",]$Gene,
                        "HD Allograft vs HD Ctr" = allDE[allDE$Label == "HD Allograft vs HD Ctr",]$Gene)

rescueVennGenes <- lapply(rescueVennGenes, as.character)


rescueVennGG <- ggVennDiagram(rescueVennGenes, label = "count", label_alpha = 1, ) + theme(legend.position = "none")+ scale_fill_gradient(low="white",high = "white") + scale_colour_manual(values = c("dodgerblue", "forestgreen", "orange", "darkorchid3"))

rescueVennGG



```

# Make G2M Plot and calculate statistics

```{r}

metaMerged <- merged@meta.data
cellTypes <- c("cGPC", "GPC")
names(metaMerged)

cellCycleDF <- metaMerged[,c("S.Score", "G2M.Score", "Phase", "otherGroup", "CellType", "newLabel", "Transplant", "Cell")]
cellCycleDF <- cellCycleDF[cellCycleDF$CellType %in% cellTypes,]

allograftBoxPlot <- ggplot(cellCycleDF[cellCycleDF$otherGroup %in% c("G19 Adult Alone Late", "G19 Adult Rescue", "G20 Neonatal Alone Late", "G20 Neonatal Rescue"),], aes(fill = newLabel, y = G2M.Score)) + geom_boxplot(notch = T, outlier.shape = NA) +
  ylim(c(-.18,.11)) + theme_classic() + ylab("G2M Score") + NoLegend()

allograftBoxPlot

dunnTest(data = cellCycleDF[cellCycleDF$otherGroup %in% c("G19 Adult Alone Late", "G19 Adult Rescue", "G20 Neonatal Alone Late", "G20 Neonatal Rescue"),],
         method = "bh",
         G2M.Score ~ newLabel)

sourceData2E <- cellCycleDF[cellCycleDF$otherGroup %in% c("G19 Adult Alone Late", "G19 Adult Rescue", "G20 Neonatal Alone Late", "G20 Neonatal Rescue"),]
sourceData2E <- sourceData2E[,c(2,5,6)]
sourceData2E$cellName <- row.names(sourceData2E)

#write.xlsx("SourceData/Fig2SourceData.xlsx", sheetName = "Fig2E", x = sourceData2E, row.names = F, append = T)




```

# Lay out top of figure

```{r}

table(g20RescueSubset$Label)
dim(g20RescueSubset)
integratedAllograftGG <- DimPlotCustom(g20RescueSubset, group.by = "CellType") + scale_fill_manual(values = dimPlotColors) + ggtitle("Integrated - 3632 Cells") + coord_flip() + scale_y_reverse()
splitAllograftGG <- DimPlotCustom(g20RescueSubset, group.by = "CellType", split.by = "Label", nrow = 2) & NoLegend() & theme(axis.title = element_blank()) & scale_fill_manual(values = dimPlotColors) & coord_flip() & scale_y_reverse()

splitAllograftGG[[1]] <- splitAllograftGG[[1]] + ggtitle("WT Ctr - 2644 Cells")
splitAllograftGG[[2]] <- splitAllograftGG[[2]] + ggtitle("WT Allograft - 548 Cells")
splitAllograftGG[[3]] <- splitAllograftGG[[3]] + ggtitle("HD Ctr - 234 Cells")
splitAllograftGG[[4]] <- splitAllograftGG[[4]] + ggtitle("HD Allograft - 206 Cells")



(plot_spacer() / integratedAllograftGG) | splitAllograftGG | stackedPlotG20Rescue | (allograftBoxPlot / rescueVennGG)



```

# Make IPA Graph
```{r}
GO <- read.csv("data_for_import/GO.csv")
GOlevels <- c("WT Ctr vs HD Ctr", "WT Allograft vs HD Allograft", "WT Allograft vs WT Ctr", "HD Allograft vs HD Ctr",
              "Young WT Ctr vs Aged WT Ctr", "Young WT Isograft vs Aged WT Isograft", "Young WT Isograft vs Young WT Ctr", "Aged WT Isograft vs Aged WT Ctr")

goCats <- c("EIF2 Signaling", "LARP1 Signaling", "MLXIPL Signaling", "mTOR Signaling", "MYC Signaling", "MYCN Signaling", "Oxidative Phosphorylation", "RICTOR Signaling", "Synthesis of protein", "TP53 Signaling", "YAP1 Signaling")

GO$Signaling <- factor(GO$Signaling, levels = goCats)
GO$Label <- factor(GO$Label, levels = GOlevels)



allograftGG <- ggplot(GO[GO$Paradigm == "Allograft",]) +
  geom_point(aes(x = Label, y = Signaling, size = Pval, colour = Zscore)) +
  scale_colour_gradient2(low = "green4", mid = "grey", high = "red2", midpoint = 0, guide = guide_colourbar(direction = "vertical", title = "Activation\nZ-Score", title.position = "left", title.hjust = .5)) +
  theme_bw() +
  theme(legend.position = "bottom", axis.title.x = element_blank(), axis.title.y = element_blank(), legend.box = "horizontal", axis.text.y = element_text(size = 10), legend.title = element_text(angle = 90)) +
  labs(size="-Log10 P-Value") + scale_size(range = c(0,12), limits = c(0,60),breaks = c(15, 39, 45,60)) 

allograftGG

sourceData2G <- GO[GO$Paradigm == "Allograft",]
sourceData2G <- sourceData2G[,c(3,4,5,6,8)]
                   
#write.xlsx("SourceData/Fig2SourceData.xlsx", sheetName = "Fig2G", x = sourceData2G, row.names = F, append = T)
                   
```

# Make HM of curated Genes

```{r}

allLogFC <- read.delim("DE/allLogFC.txt")
allLogFC$Label <- factor(allLogFC$Label, levels = GOlevels)

makeHM <- function(genes, paradigm, returnGG = T){
  temp <- allLogFC[allLogFC$Gene %in% genes & allLogFC$Paradigm == paradigm,]
  temp$sig <- ifelse(temp$FDR < 0.0001 & abs(temp$logFC) > 0.15, yes = "****", 
                     ifelse(temp$FDR < 0.001 & abs(temp$logFC) > 0.15, yes = "***",
                            ifelse(temp$FDR < 0.01 & abs(temp$logFC) > 0.15, yes = "**",
                                   ifelse(temp$FDR < 0.05 & abs(temp$logFC) > 0.15, yes = "*", no = ""))))
  tempCluster <- temp[,c("Gene", "Label", "logFC")] %>% pivot_wider(values_from = "logFC", names_from = "Label")
  tempCluster <- data.frame(row.names = tempCluster$Gene, tempCluster[,2:5])
  tempClusterOrder <- hclust(dist(tempCluster))$order
  tempClusterOrder <- row.names(tempCluster)[tempClusterOrder]
  temp$Gene <- factor(temp$Gene, levels = tempClusterOrder)
  if(returnGG == T) {
    return(ggplot(temp, aes(fill = logFC, x = Label, y = Gene)) + geom_tile() + scale_fill_gradient2(low = "forestgreen", mid = "lightgrey", high = "red2", midpoint = 0) +
           scale_x_discrete(expand = c(0,0)) + theme(legend.position = "left", axis.title = element_blank())  + geom_text(aes(label=sig, vjust = 1)))  
  } else {
    return(temp)
  }
}

rescueGenes <- c("HSPA1B", "DNAJB1", "OLIG1", "HLA-A", "HLA-C", "GRIA4", "LY6H", "NEU4", "YWHAB", "MT3", "MIF", "B2M", "SPARCL1", "SPARC", "LINGO1", "JUNB", "PCDHGB6", "CALM1", "CASK", "IER2", "HBD", "SLITRK2")



rescueHM <- makeHM(rescueGenes, "Allograft", returnGG = T)
rescueHM

sourceData2H <- makeHM(rescueGenes, "Allograft", returnGG = F)
sourceData2H <- sourceData2H[,c(2,4,5,6,8)]


#write.xlsx("SourceData/Fig2SourceData.xlsx", sheetName = "Fig2H", x = sourceData2H, row.names = F, append = T)

```

# Make Ribosomal Violins

```{r}

allDE$Label <- factor(allDE$Label, levels = GOlevels)
riboRescue <- allDE[allDE$Gene %in% unique(grep(paste(c("RPS", "RPL"),collapse="|"), 
                                                      allDE$Gene, value=TRUE)) & allDE$Paradigm == "Allograft",]
riboRescue <- riboRescue[riboRescue$Gene %not in% c("PRPSAP1", "TRPS1"),]

riboRescueGG <- ggplot(riboRescue, aes(Label, Log2FC)) +
  geom_violin(aes(fill = Label)) + theme_bw() +  theme(legend.position = "none", axis.title.x = element_blank(), axis.text.x = element_blank())  +scale_fill_manual(values = c("dodgerblue", "forestgreen", "orange", "darkorchid3")) +
  ylab("DE Ribosomal Gene\nLog2 Fold Change")

riboRescueGG

sourceData2I <- riboRescue[,c(2:5,7)]
#write.xlsx("SourceData/Fig2SourceData.xlsx", sheetName = "Fig2I", x = sourceData2I, row.names = F, append = T)


```

# Save Top and Bottom of figure

```{r} 
((plot_spacer() / integratedAllograftGG) | splitAllograftGG | stackedPlotG20Rescue | (allograftBoxPlot / rescueVennGG)) + plot_layout(widths = c(1,1,.5,.8))
ggsave("Figures/AllograftTop.pdf", width = 12, height = 6)


allograftGG |(rescueHM/ riboRescueGG) + plot_layout(heights = c(3,1))
ggsave("Figures/AllograftBottom.pdf", width = 12, height = 6)


```

```{r}

sessionInfo()

```